import { execSync } from "node:child_process";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { writeFile } from "node:fs/promises";
import { config } from "dotenv";
import EmbeddedPostgres from "embedded-postgres";
import pg from "pg";
import {
  TEST_DATABASE_NAME,
  rewriteDatabaseUrlForTests,
} from "../src/config/testDatabaseUrl.js";

const serverRoot = fileURLToPath(new URL("..", import.meta.url));

const loadLocalEnv = () => {
  config({
    path: fileURLToPath(new URL("../.env.local", import.meta.url)),
  });
};

const adminConnectionUrl = (databaseUrl: string) => {
  const parsed = new URL(databaseUrl);
  parsed.pathname = "/postgres";
  return parsed.toString();
};

const canConnect = async (databaseUrl: string) => {
  const client = new pg.Client({
    connectionString: adminConnectionUrl(databaseUrl),
    connectionTimeoutMillis: 2_000,
  });
  try {
    await client.connect();
    await client.end();
    return true;
  } catch {
    return false;
  }
};

const ensureNamedDatabase = async (databaseUrl: string, name: string) => {
  const client = new pg.Client({
    connectionString: adminConnectionUrl(databaseUrl),
  });
  await client.connect();
  try {
    const result = await client.query<{ exists: boolean }>(
      "SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = $1) AS exists",
      [name],
    );
    if (!result.rows[0]?.exists) {
      await client.query(`CREATE DATABASE "${name}"`);
    }
  } finally {
    await client.end();
  }
};

const writeTestEnv = async (databaseUrl: string) => {
  const jwt =
    process.env.JWT_SECRET && process.env.JWT_SECRET.length >= 32
      ? process.env.JWT_SECRET
      : "test-jwt-secret-must-be-at-least-32ch";
  const lines = [
    "# Generated by test/globalSetup.ts — do not commit",
    `DATABASE_URL="${databaseUrl}"`,
    `JWT_SECRET="${jwt}"`,
    `CLIENT_URL="${process.env.CLIENT_URL ?? "http://localhost:5173"}"`,
    `NODE_ENV="test"`,
    `SUPER_ADMIN_EMAIL="${process.env.SUPER_ADMIN_EMAIL ?? "superadmin@fms.test"}"`,
    `SUPER_ADMIN_PASSWORD="${process.env.SUPER_ADMIN_PASSWORD ?? "password123"}"`,
    `SUPER_ADMIN_NAME="${process.env.SUPER_ADMIN_NAME ?? "Test Super Admin"}"`,
    `JWT_COOKIE_NAME="${process.env.JWT_COOKIE_NAME ?? "fms_token"}"`,
    "",
  ];
  await writeFile(path.join(serverRoot, ".env.test"), lines.join("\n"), "utf8");
};

const startEmbeddedPostgres = async () => {
  const databaseDir = await mkdtemp(path.join(tmpdir(), "fms-pg-"));
  const port = 55_000 + Math.floor(Math.random() * 1_000);
  const user = "postgres";
  const password = "postgres";
  const cluster = new EmbeddedPostgres({
    databaseDir,
    user,
    password,
    port,
    persistent: false,
    onLog: () => {},
  });
  await cluster.initialise();
  await cluster.start();
  await cluster.createDatabase(TEST_DATABASE_NAME);
  const databaseUrl = `postgresql://${user}:${password}@127.0.0.1:${port}/${TEST_DATABASE_NAME}?schema=public`;
  return { cluster, databaseUrl };
};

export default async function globalSetup() {
  loadLocalEnv();
  process.env.NODE_ENV = "test";

  if (!process.env.DATABASE_URL) {
    throw new Error(
      "DATABASE_URL is missing. Copy server/.env.local.example to server/.env.local.",
    );
  }

  let testUrl = rewriteDatabaseUrlForTests(process.env.DATABASE_URL);
  let cluster: EmbeddedPostgres | undefined;

  if (await canConnect(process.env.DATABASE_URL)) {
    await ensureNamedDatabase(testUrl, TEST_DATABASE_NAME);
  } else {
    console.warn(
      "Local Postgres is not reachable; starting embedded Postgres for tests.",
    );
    const embedded = await startEmbeddedPostgres();
    cluster = embedded.cluster;
    testUrl = embedded.databaseUrl;
  }

  process.env.DATABASE_URL = testUrl;
  await writeTestEnv(testUrl);

  execSync("npx prisma migrate deploy", {
    cwd: serverRoot,
    env: { ...process.env, DATABASE_URL: testUrl },
    stdio: "inherit",
  });

  return async () => {
    if (cluster) {
      await cluster.stop();
    }
  };
}
